ALTER TABLE users
ADD COLUMN added_by BIGINT UNSIGNED DEFAULT NULL,
ADD COLUMN edited_by BIGINT UNSIGNED DEFAULT NULL,
MODIFY COLUMN middle_name VARCHAR(25) DEFAULT NULL;

ALTER TABLE users 
ADD CONSTRAINT fk_users_added_by
FOREIGN KEY (added_by)
REFERENCES users(id)
ON DELETE CASCADE;

ALTER TABLE users
ADD CONSTRAINT fk_users_updated_by
FOREIGN KEY (edited_by)
REFERENCES users(id)
ON DELETE SET NULL;
